"""Generate Phase 2 COSMOS paper-convergence extendedness figures."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

from paper_extendedness import (
    compare_extendedness_metrics,
    plot_confusion_cmd,
    plot_extendedness_color_color,
    plot_extendedness_performance,
    verify_extendedness_convention,
)
from paper_sample_selection import prepare_phase1_samples


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _append_manifest(repo_root: Path, generated: list[dict]) -> None:
    manifest = repo_root / "paper_convergence/docs/figure_manifest.md"
    existing = manifest.read_text(encoding="utf-8") if manifest.exists() else "# Figure Manifest\n"
    marker = "\n## Phase 2: Extendedness Baselines\n"
    content = existing.split(marker)[0].rstrip() + marker
    for row in generated:
        content += (
            f"\n### {row['figure_id']}\n"
            f"- Filename: `{row['filename']}`\n"
            f"- Generated by: `paper_convergence/code/run_paper_phase2_cosmos.py`\n"
            f"- Caption draft: {row['caption']}\n"
            f"- Sample definition: {row['sample']}\n"
            f"- Caveats: {row['caveats']}\n"
            f"- Status: {row['status']}\n"
        )
    _write_text(manifest, content + "\n")


def run_phase2(repo_root: Path) -> dict[str, list[Path]]:
    samples = prepare_phase1_samples(repo_root)
    dp2_paper = samples["dp2_paper"]
    matched_paper = samples["matched_paper"]

    out_fig = repo_root / "paper_convergence/figures/section1_extendedness"
    out_res = repo_root / "paper_convergence/results/section1_extendedness"
    out_log = repo_root / "paper_convergence/logs"
    out_fig.mkdir(parents=True, exist_ok=True)
    out_res.mkdir(parents=True, exist_ok=True)
    out_log.mkdir(parents=True, exist_ok=True)

    conventions = verify_extendedness_convention(matched_paper, ("dp2_extendedness_r", "dp2_refExtendedness"))
    convention_path = out_res / "extendedness_convention_check.csv"
    conventions.to_csv(convention_path, index=False)

    required = ["extendedness_r", "refExtendedness"]
    missing = [col for col in required if col not in dp2_paper.columns]
    matched_required = ["dp2_extendedness_r", "dp2_refExtendedness"]
    missing += [col for col in matched_required if col not in matched_paper.columns]
    if missing:
        raise RuntimeError(f"Missing required extendedness columns: {missing}")

    outputs: dict[str, list[Path]] = {"convention_check": [convention_path]}

    fig, summary = plot_extendedness_color_color(
        dp2_paper,
        "extendedness_r",
        "r-band extendedness",
        out_fig / "fig1_4_cosmos_r_extendedness_color_color_2x4.png",
    )
    path = out_res / "fig1_4_cosmos_r_extendedness_color_color_2x4_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig1_4_r_extendedness"] = fig + [path]

    fig, summary = plot_extendedness_color_color(
        dp2_paper,
        "refExtendedness",
        "refExtendedness",
        out_fig / "fig1_4_cosmos_refExtendedness_color_color_2x4.png",
    )
    path = out_res / "fig1_4_cosmos_refExtendedness_color_color_2x4_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig1_4_refExtendedness"] = fig + [path]

    fig, summary = plot_confusion_cmd(
        matched_paper,
        "dp2_extendedness_r",
        "r-band extendedness",
        out_fig / "fig1_5_cosmos_r_extendedness_confusion_cmd_4panel.png",
    )
    path = out_res / "fig1_5_cosmos_r_extendedness_confusion_cmd_4panel_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig1_5_r_extendedness"] = fig + [path]

    fig, summary = plot_confusion_cmd(
        matched_paper,
        "dp2_refExtendedness",
        "refExtendedness",
        out_fig / "fig1_5_cosmos_refExtendedness_confusion_cmd_4panel.png",
    )
    path = out_res / "fig1_5_cosmos_refExtendedness_confusion_cmd_4panel_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig1_5_refExtendedness"] = fig + [path]

    fig, r_metrics = plot_extendedness_performance(
        matched_paper,
        "dp2_extendedness_r",
        "r-band extendedness",
        out_fig / "fig1_6_cosmos_r_extendedness_roc_3bins.png",
    )
    r_path = out_res / "fig1_6_cosmos_r_extendedness_roc_3bins_summary.csv"
    r_metrics.to_csv(r_path, index=False)
    outputs["fig1_6_r_extendedness"] = fig + [r_path]

    fig, ref_metrics = plot_extendedness_performance(
        matched_paper,
        "dp2_refExtendedness",
        "refExtendedness",
        out_fig / "fig1_6_cosmos_refExtendedness_roc_3bins.png",
    )
    ref_path = out_res / "fig1_6_cosmos_refExtendedness_roc_3bins_summary.csv"
    ref_metrics.to_csv(ref_path, index=False)
    outputs["fig1_6_refExtendedness"] = fig + [ref_path]

    comp, comp_md = compare_extendedness_metrics(r_metrics, ref_metrics)
    comp_csv = out_res / "extendedness_vs_refExtendedness_comparison_summary.csv"
    comp_doc = out_res / "extendedness_vs_refExtendedness_comparison_summary.md"
    comp.to_csv(comp_csv, index=False)
    _write_text(comp_doc, comp_md)
    outputs["comparison_summary"] = [comp_csv, comp_doc]

    manifest_rows = [
        {
            "figure_id": "Fig 1.4 r extendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_4_cosmos_r_extendedness_color_color_2x4.png",
            "caption": "COSMOS color-color diagrams split by r-band extendedness classification.",
            "sample": "COSMOS DP2 paper sample; 16 < uncorrected r CModelMag < 26.",
            "caveats": "NaN/other extendedness values are excluded from plotted classes and counted in the summary.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 1.4 refExtendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_4_cosmos_refExtendedness_color_color_2x4.png",
            "caption": "COSMOS color-color diagrams split by refExtendedness classification.",
            "sample": "COSMOS DP2 paper sample; 16 < uncorrected r CModelMag < 26.",
            "caveats": "NaN/other refExtendedness values are excluded from plotted classes and counted in the summary.",
            "status": "appendix candidate",
        },
        {
            "figure_id": "Fig 1.5 r extendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_5_cosmos_r_extendedness_confusion_cmd_4panel.png",
            "caption": "COSMOS2020 truth versus r-band extendedness classification in a g-i CMD.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "x-axis uses dust-corrected g-i; y-axis uses uncorrected r CModelMag.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 1.5 refExtendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_5_cosmos_refExtendedness_confusion_cmd_4panel.png",
            "caption": "COSMOS2020 truth versus refExtendedness classification in a g-i CMD.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "x-axis uses dust-corrected g-i; y-axis uses uncorrected r CModelMag.",
            "status": "appendix candidate",
        },
        {
            "figure_id": "Fig 1.6 r extendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_6_cosmos_r_extendedness_roc_3bins.png",
            "caption": "Binary r-band extendedness operating-point ROC metrics in three r-magnitude bins.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "Extendedness is binary; plotted curves are step/operating-point ROC diagnostics, not smooth ROC curves.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 1.6 refExtendedness",
            "filename": "paper_convergence/figures/section1_extendedness/fig1_6_cosmos_refExtendedness_roc_3bins.png",
            "caption": "Binary refExtendedness operating-point ROC metrics in three r-magnitude bins.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "refExtendedness is binary; plotted curves are step/operating-point ROC diagnostics, not smooth ROC curves.",
            "status": "appendix candidate",
        },
    ]
    _append_manifest(repo_root, manifest_rows)

    lines = [
        "# Phase 2 Generation Summary",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "## Completed",
    ]
    for key, paths in outputs.items():
        lines.append(f"- {key}:")
        for path in paths:
            lines.append(f"  - `{path.relative_to(repo_root)}`")
    lines += [
        "",
        "## Verified Conventions",
        "- `0=unresolved/star-like`, `1=resolved/galaxy-like` for `dp2_extendedness_r` and `dp2_refExtendedness`.",
        "- The convention check is recorded in `paper_convergence/results/section1_extendedness/extendedness_convention_check.csv`.",
        "",
        "## Assumptions And Caveats",
        "- NaN/other extendedness values are excluded from classification plots and metrics, and counted in summary tables.",
        "- Fig 1.6 uses binary operating-point ROC curves because extendedness/refExtendedness are binary classifiers.",
        "- Fig 1.5 uses dust-corrected g-i color to match the existing CMD confusion style.",
    ]
    summary_path = out_log / "phase2_generation_summary.md"
    _write_text(summary_path, "\n".join(lines) + "\n")
    outputs["logs"] = [summary_path]
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    outputs = run_phase2(args.repo_root.resolve())
    print("[PHASE 2 COMPLETE]")
    for key, paths in outputs.items():
        print(f"{key}:")
        for path in paths:
            print(f"  {path}")


if __name__ == "__main__":
    main()

