"""Generate Phase 1 COSMOS paper-convergence figures.

This script creates the infrastructure and Section 1.1-1.3 outputs for the
COSMOS/COSMOS2020 paper sample. It reads local parquet/CSV data but only writes
small figure and summary outputs under paper_convergence/.
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import pandas as pd

from paper_color_plots import plot_fig1_1, plot_fig1_2, plot_fig1_3
from paper_matching_diagnostics import cosmos_matching_radius_sweep
from paper_sample_selection import (
    COSMOS_DEC_RANGE,
    COSMOS_RA_RANGE,
    EXTINCTION_SCALE,
    PAPER_RMAG_RANGE,
    PaperPaths,
    build_sample_counts,
    prepare_phase1_samples,
    verify_phase1_conventions,
)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _init_docs(repo_root: Path) -> None:
    pc_root = repo_root / "paper_convergence"
    readme = pc_root / "README.md"
    if not readme.exists():
        _write_text(
            readme,
            """# Paper Convergence

This folder contains the paper-convergence pipeline for the Rubin star-galaxy separation project.

- Primary paper sample: COSMOS DP2 matched to COSMOS2020 external labels.
- ECDFS/HST is secondary and can be rerun later as a comparison.
- Figures are in `figures/`.
- Numerical summaries are in `results/`.
- Notebooks are in `notebooks/`.
- Reusable paper-specific code is in `code/`.
- Private data, FITS files, parquet catalogs, and large Rubin catalog files are not stored here.
- Main sample selection uses uncorrected r-band CModel magnitude.
- Colors are computed from CModel magnitudes corrected for dust extinction with the existing repo extinction convention.
- Shared plot style is centralized in `paper_convergence/code/paper_plot_style.py`.
""",
        )

    manifest = pc_root / "docs/figure_manifest.md"
    if not manifest.exists():
        _write_text(
            manifest,
            """# Figure Manifest

This manifest tracks paper-convergence figures, their generating code, sample definitions, and caveats.
""",
        )


def _append_manifest(repo_root: Path, generated: list[dict]) -> None:
    manifest = repo_root / "paper_convergence/docs/figure_manifest.md"
    existing = manifest.read_text(encoding="utf-8") if manifest.exists() else "# Figure Manifest\n"
    marker = "\n## Phase 1: COSMOS Dataset And Truth Labels\n"
    content = existing.split(marker)[0].rstrip() + marker
    for row in generated:
        content += (
            f"\n### {row['figure_id']}\n"
            f"- Filename: `{row['filename']}`\n"
            f"- Generated by: `paper_convergence/code/run_paper_phase1_cosmos.py`\n"
            f"- Caption draft: {row['caption']}\n"
            f"- Sample definition: COSMOS coordinate cut; 16 < uncorrected r CModelMag < 26 where applicable.\n"
            f"- Caveats: {row['caveats']}\n"
            f"- Status: {row['status']}\n"
        )
    _write_text(manifest, content + "\n")


def _write_sample_definition(repo_root: Path, paths: PaperPaths, counts: pd.DataFrame, conventions: dict[str, str]) -> None:
    text = f"""# COSMOS Paper Sample Definition

Generated: {datetime.now().isoformat(timespec='seconds')}

## Input Files

- DP2 analysis table: `{paths.dp2_table.relative_to(repo_root)}`
- DP2/COSMOS2020 matched table: `{paths.matched_table.relative_to(repo_root)}`
- COSMOS2020 truth catalog: `{paths.external_truth.relative_to(repo_root)}`

These input parquet/catalog files are local data dependencies and should not be committed.

## Cuts

- Field: COSMOS
- External labels: COSMOS2020 FARMER truth labels
- Coordinate cut: {COSMOS_RA_RANGE[0]} < RA < {COSMOS_RA_RANGE[1]}, {COSMOS_DEC_RANGE[0]} < Dec < {COSMOS_DEC_RANGE[1]}
- Magnitude cut: {PAPER_RMAG_RANGE[0]} < uncorrected r-band CModel magnitude < {PAPER_RMAG_RANGE[1]}

## Verified Conventions

Truth-label convention from matched table:

```text
{conventions['truth_binary']}
```

Dust/color convention:

{conventions['extinction']}

Extinction scale: Ar = ebv * {EXTINCTION_SCALE:.8f}

COSMOS2020-only magnitude limitation:

{conventions['cosmos2020_only_magnitude']}

## Counts

See `paper_convergence/results/section1_dataset/cosmos_paper_sample_counts.csv`.
"""
    out_dir = repo_root / "paper_convergence/results/section1_dataset"
    _write_text(out_dir / "cosmos_paper_sample_definition.md", text)
    counts.to_csv(out_dir / "cosmos_paper_sample_counts.csv", index=False)


def run_phase1(repo_root: Path) -> dict[str, list[Path]]:
    _init_docs(repo_root)
    paths = PaperPaths.from_repo_root(repo_root)
    samples = prepare_phase1_samples(repo_root)
    counts = build_sample_counts(samples)
    conventions = verify_phase1_conventions(samples)
    _write_sample_definition(repo_root, paths, counts, conventions)

    outputs: dict[str, list[Path]] = {}

    fig1_1, fig1_1_summary = plot_fig1_1(
        samples,
        repo_root / "paper_convergence/figures/section1_dataset/fig1_1_cosmos_dataset_overview.png",
    )
    fig1_1_summary.to_csv(repo_root / "paper_convergence/results/section1_dataset/fig1_1_cosmos_dataset_overview_counts.csv", index=False)
    outputs["fig1_1"] = fig1_1 + [repo_root / "paper_convergence/results/section1_dataset/fig1_1_cosmos_dataset_overview_counts.csv"]

    sweep = cosmos_matching_radius_sweep(samples["dp2"], samples["external"])
    sweep.to_csv(repo_root / "paper_convergence/results/diagnostics/cosmos_matching_radius_sweep.csv", index=False)
    # Plot after CSV creation so the table is available even if plotting fails.
    import matplotlib.pyplot as plt
    from paper_plot_style import COLORS, FIG_SIZES, save_figure, set_paper_style

    set_paper_style()
    fig, ax = plt.subplots(figsize=(8.2, 5.2))
    fig.subplots_adjust(left=0.10, right=0.98, bottom=0.14, top=0.88)
    ax.plot(sweep["radius_arcsec"], sweep["match_fraction_relative_to_external"], marker="o", color=COLORS["external_only"], label="matched / external")
    ax.plot(
        sweep["radius_arcsec"],
        sweep["match_fraction_relative_to_DP2_inside_external_footprint"],
        marker="s",
        color=COLORS["dp2_only"],
        label="unique matched DP2 / DP2 in rectangular cut",
    )
    ax.set_xlabel("matching radius (arcsec)")
    ax.set_ylabel("fraction")
    ax.set_title("COSMOS matching-radius sweep")
    ax.legend(loc="best", frameon=True)
    radius_fig = save_figure(fig, repo_root / "paper_convergence/figures/diagnostics/cosmos_matching_radius_sweep.png")
    outputs["matching_radius_sweep"] = radius_fig + [repo_root / "paper_convergence/results/diagnostics/cosmos_matching_radius_sweep.csv"]

    fig1_2, fig1_2_summary = plot_fig1_2(
        samples,
        repo_root / "paper_convergence/figures/section1_truth_labels/fig1_2_cosmos_truth_morphology_color_2x2.png",
    )
    fig1_2_summary.to_csv(repo_root / "paper_convergence/results/section1_truth_labels/fig1_2_cosmos_truth_morphology_color_2x2_summary.csv", index=False)
    outputs["fig1_2"] = fig1_2 + [repo_root / "paper_convergence/results/section1_truth_labels/fig1_2_cosmos_truth_morphology_color_2x2_summary.csv"]

    fig1_3, fig1_3_summary = plot_fig1_3(
        samples,
        repo_root / "paper_convergence/figures/section1_truth_labels/fig1_3_cosmos_truth_color_color_2x4.png",
    )
    fig1_3_summary.to_csv(repo_root / "paper_convergence/results/section1_truth_labels/fig1_3_cosmos_truth_color_color_2x4_summary.csv", index=False)
    outputs["fig1_3"] = fig1_3 + [repo_root / "paper_convergence/results/section1_truth_labels/fig1_3_cosmos_truth_color_color_2x4_summary.csv"]

    generated_manifest = [
        {
            "figure_id": "Fig 1.1",
            "filename": "paper_convergence/figures/section1_dataset/fig1_1_cosmos_dataset_overview.png",
            "caption": "COSMOS DP2 and COSMOS2020 matched sample overview: sky distribution, counts vs uncorrected r CModel magnitude, and r-band flux uncertainty ratio.",
            "caveats": "COSMOS2020-only counts use HSC_r_MAG when the local full FARMER FITS is available; otherwise this curve is omitted.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Diagnostic",
            "filename": "paper_convergence/figures/diagnostics/cosmos_matching_radius_sweep.png",
            "caption": "Nearest-neighbor matching fraction as a function of matching radius.",
            "caveats": "DP2 denominator uses the rectangular COSMOS coordinate cut.",
            "status": "diagnostic only",
        },
        {
            "figure_id": "Fig 1.2",
            "filename": "paper_convergence/figures/section1_truth_labels/fig1_2_cosmos_truth_morphology_color_2x2.png",
            "caption": "COSMOS2020 truth-label stars and galaxies in morphology, color-magnitude, and color-color spaces.",
            "caveats": "Colors use existing repo dust-correction coefficients.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 1.3",
            "filename": "paper_convergence/figures/section1_truth_labels/fig1_3_cosmos_truth_color_color_2x4.png",
            "caption": "COSMOS2020 truth-label color-color diagrams split into bright and faint r-magnitude ranges.",
            "caveats": "Uses fixed Week10 color-color axis ranges.",
            "status": "main paper candidate",
        },
    ]
    _append_manifest(repo_root, generated_manifest)

    summary_lines = [
        "# Phase 1 Generation Summary",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "## Completed",
    ]
    for key, paths_out in outputs.items():
        summary_lines.append(f"- {key}:")
        for path in paths_out:
            summary_lines.append(f"  - `{path.relative_to(repo_root)}`")
    summary_lines += [
        "",
        "## Assumptions And Caveats",
        "- COSMOS2020 labels use `truth_binary == 1` for stars and `truth_binary == 0` for galaxies.",
        "- r-band CModel magnitude used for sample selection is not dust-corrected.",
        "- Dust-corrected colors use `magnitude_calc.extcoeff()` and `Ar = ebv * 3.10 / 1.20`.",
        "- COSMOS2020-only objects in Fig 1.1b use `HSC_r_MAG` from the local full FARMER FITS when available; this is labelled separately from DP2 r CModelMag.",
        "- Scatter panels downsample dense galaxy samples for plotting only; CSV counts use full samples.",
    ]
    _write_text(repo_root / "paper_convergence/logs/phase1_generation_summary.md", "\n".join(summary_lines) + "\n")
    outputs["docs"] = [
        repo_root / "paper_convergence/README.md",
        repo_root / "paper_convergence/docs/figure_manifest.md",
        repo_root / "paper_convergence/results/section1_dataset/cosmos_paper_sample_definition.md",
        repo_root / "paper_convergence/results/section1_dataset/cosmos_paper_sample_counts.csv",
        repo_root / "paper_convergence/logs/phase1_generation_summary.md",
    ]
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    outputs = run_phase1(args.repo_root.resolve())
    print("[PHASE 1 COMPLETE]")
    for key, paths in outputs.items():
        print(f"{key}:")
        for path in paths:
            print(f"  {path}")


if __name__ == "__main__":
    main()
